### ISSUE TITLE
Crash After New Update

### ISSUE THREAD

**Issue by ereese99** [Corosauce/WATUT#21]
**Describe the bug**
It was either as I was opening up an inventory or typing, my game suddenly crashed.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-02-12 10:37:57
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'watut'!
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at MC//net.minecraft.client.MinecraftClient.redirect$ion000$notenoughcrashes$catchFabricInit(MinecraftClient.java:37527)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: com/corosus/modconfig/IConfigCategory
	at java.base@17.0.8/java.lang.Class.forName0(Native Method)
	at java.base@17.0.8/java.lang.Class.forName(Class.java:467)
	at app//net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.corosus.modconfig.IConfigCategory
	at java.base@17.0.8/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base@17.0.8/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base@17.0.8/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 14 more

**Mod and Minecraft version:**
 - Version: Minecraft 1.20.1, Fabric 0.15.6, WATUT 1.1.0

**Comment by Mozork01** [comment]
For me, the game crashes upon launch.

**Comment by Corosauce** [comment]
Fixed with coroutil-fabric-1.20.1-1.3.7.jar which is being pushed to curse right now.
