### ISSUE TITLE
Server crashes on player joining

### ISSUE THREAD

**Issue by Partonetrain** [Corosauce/WATUT#38]
**Describe the bug**
When trying to join a server, the client disconnects and the server crashes.

**To Reproduce**
1. Install mod on both Client and Server
2. Join Server
3. See issue

**latest.log, debug.log or crash report if the other 2 arent possible**
```
[19:55:09] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/class_3999
        at com.corosus.watut.PlayerStatus.<init>(PlayerStatus.java:143) ~[watut-fabric-1.20.1-1.1.2.jar:?]
        at com.corosus.watut.PlayerStatusManager.getStatus(PlayerStatusManager.java:40) ~[watut-fabric-1.20.1-1.1.2.jar:?]
        at com.corosus.watut.PlayerStatusManager.getStatus(PlayerStatusManager.java:33) ~[watut-fabric-1.20.1-1.1.2.jar:?]
        at com.corosus.watut.PlayerStatusManager.getStatus(PlayerStatusManager.java:29) ~[watut-fabric-1.20.1-1.1.2.jar:?]
        at com.corosus.watut.PlayerStatusManagerServer.handleIdleState(PlayerStatusManagerServer.java:67) ~[watut-fabric-1.20.1-1.1.2.jar:?]
        at com.corosus.watut.PlayerStatusManagerServer.receiveAny(PlayerStatusManagerServer.java:40) ~[watut-fabric-1.20.1-1.1.2.jar:?]
        at com.corosus.watut.loader.fabric.WatutModFabric.lambda$onInitialize$1(WatutModFabric.java:30) ~[watut-fabric-1.20.1-1.1.2.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3999
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 20 more
```

**Expected behavior**
No crash

**Screenshots**
![image](https://github.com/user-attachments/assets/6c52b2a8-020a-4fee-8ad1-13d9ad834d0d)

**Mod and Minecraft version:**
Without this your issue will likely get closed for lacking enough info.
watut-fabric-1.20.1-1.1.2
Fabric-0.15.11

**Additional context**
intermediary 3999 = yarn net.minecraft.client.particle.ParticleTextureSheet

**Comment by Corosauce** [comment]
Fixed with 1.1.3
