### ISSUE TITLE
Conflicting with Better Ping Display [Fabric]

### ISSUE THREAD

**Issue by SettingDust** [Corosauce/WATUT#8]
https://modrinth.com/mod/better-ping-display-fabric

https://github.com/vladmarica/better-ping-display-fabric/issues/36

`[13:28:39] [Render thread/WARN] (FabricLoader/Mixin) @Redirect conflict. Skipping betterpingdisplay.mixins.json:PlayerListHudMixin from mod betterpingdisplay->@Redirect::redirectRenderLatencyIconCall(Lnet/minecraft/class_355;Lnet/minecraft/class_332;IIILnet/minecraft/class_640;)V with priority 1000, already redirected by watut_fabric.mixins.json:client.RenderPingIconInject from mod watut->@Redirect::renderPingIcon(Lnet/minecraft/class_355;Lnet/minecraft/class_332;IIILnet/minecraft/class_640;)V with priority 1000
`

```
java.lang.RuntimeException: Mixin transformation of net.minecraft.client.gui.hud.PlayerListHud failed
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base@17.0.8/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at MC//net.minecraft.client.gui.hud.InGameHud.<init>(InGameHud.java:144)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:603)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at app//org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at app//org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at app//org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 13 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectRenderLatencyIconCall(Lnet/minecraft/client/gui/hud/PlayerListHud;Lnet/minecraft/client/gui/DrawContext;IIILnet/minecraft/client/network/PlayerListEntry;)V in betterpingdisplay.mixins.json:PlayerListHudMixin from mod betterpingdisplay failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap BetterPingDisplay-Fabric-refmap.json
	at app//org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at app//org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at app//org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at app//org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at app//org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 16 more
```

**Comment by thcprophet** [comment]
I had the same issue with a crash on boot if both mods were present.
To fix this issue what you have to do is change to _**`false`**_ the string _**`showIdleStatesInPlayerList`**_ in the config file _**`watut-client.toml`**_
What if should look like
`showIdleStatesInPlayerList = false`

**Comment by Corosauce** [comment]
Fixed with https://github.com/Corosauce/WATUT/commit/2d3e5f10350d7ee98ca727a27c724724b6aaa59e - will be fixed in watut 1.2.0+, will make sure better ping display works and my change in the code gracefully deactivates, will get ported to 1.21 version at a later time.
